name: starter
description: Navigator Demo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  animated_splash_screen: ^1.2.0
  cupertino_icons: ^1.0.4
  extended_masked_text: ^2.3.1
  flutter:
    sdk: flutter
  go_router: ^3.1.1
  icons_launcher: ^1.2.1
  provider: ^6.0.1
  shared_preferences: ^2.0.8

dev_dependencies:
  change_app_package_name: ^1.1.0

  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
 
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"
  